version: "3"
services:
  node:
    build:
      context: nodebird
      dockerfile: Dockerfile.dev
    ports:
      - "3000:8000"
    volumes:
      - /usr/src/app/node_modules
      - ./nodebird:/usr/src/app
  node_bird_api:
    build:
      context: nodebird-api
      dockerfile: Dockerfile.dev
    ports:
      - "3001:8001"
    volumes:
      - /usr/src/app/node_modules
      - ./nodebird-api:/usr/src/app
  mysql:
    build:
      context: mysql
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodebird